### ISSUE TITLE
How is the performance of this implementation?

### ISSUE THREAD

**Issue by franciscogmm** [jrzaurin/Wide-and-Deep-Keras#1]
Hey man!

How did your model do on a project/dataset of yours? Thanks!

**Comment by jrzaurin** [comment]
Hey there, 

sorry, I never saw this question! 

I used this for a recommendation algorithm, where the deep part was used as a proxy for matrix factorization (so I passed embeddings for users and items) and the wide part took "normal features" (user segments, day of the week, etc...)

It was the only algorithm that outperform xgboost (or pywFM) in terms of MAP. I was quite happy with it and as a by-product we got the embeddings that could be used by other teams in the company (for targeting, for example)

Hope it helps
