### ISSUE TITLE
Data download link is not working.

### ISSUE THREAD

**Issue by dipeshjoshi** [jrzaurin/Wide-and-Deep-Keras#3]
Data download link is not working. Can you please add data here only if its not too big?

**Comment by dipeshjoshi** [comment]
@jrzaurin Can you please have a look?

**Comment by jrzaurin** [comment]
Hi @dipeshjoshi 

I do not visit this repo that often anymore. I implemented all this in pytorch and released a package if you are interested: https://github.com/jrzaurin/pytorch-widedeep

Anyway, one can download the adult dataset from plenty of places, try here: https://www.kaggle.com/wenruliu/adult-income-dataset/
